name: Release

on:
  release:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build_exe:
    name: Build exe
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.14"
      - name: Install
        run: |
          python3 -m pip install --upgrade pip
          pip3 install . pyinstaller
          Remove-Item -Recurse -Force build
      - name: Build exe
        run: |
          nicegui-pack --name=smh-gui_$env:GITHUB_REF_NAME --onefile src/synth_mapping_helper/gui.py
      - name: Upload windows_exe
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: windows_exe
          path: dist
  upload_exe:
    name: Upload exe
    needs: build_exe
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write  # append file to release
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Download windows_exe
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8.0.1
        with:
          name: windows_exe
      - name: Upload Artifacts
        run: |
          gh release upload ${GITHUB_EVENT_RELEASE_TAG_NAME} smh-gui_${GITHUB_REF_NAME}.exe
        env:
          GITHUB_EVENT_RELEASE_TAG_NAME: ${{github.event.release.tag_name}}

  package:
    name: Create release package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Build and Check Package
      uses: hynek/build-and-inspect-python-package@d44ca7d91762de7a7d5436ddae667c6da6d1c3df
  publish:
    name: Publish to pypi
    needs: package
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write  # for trusted publishing
    steps:
      - name: Download Package
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: Packages
          path: dist
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b
        with:
          attestations: true
